mdapi/sfdx-unum-poc-alpha-deploys/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Commissionable entity with PCES ID</inlineHelpText>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRIM_FIELD_OFC_NM__c</fullName>
        <formula>IF(ISBLANK(OVRID_PRIM_FIELD_OFC_ID__c) = TRUE , Owner.Sales_Office__c , OVRID_PRIM_FIELD_OFC_ID__r.Name)</formula>
        <inlineHelpText>Automatically populated based on field  user&apos;s mailstop, does not populate for Home Office users.</inlineHelpText>
        <label>Primary Field Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PRIM_SALE_REP_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sales Rep in Field Office assigned to opportunity team</inlineHelpText>
        <label>Primary Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QUOTE_STAGE_BEGIN_DT__c</fullName>
        <description>This field captures the date/time-stamp when the Opportunity reaches the &quot;Quoting&quot; stage for the first time.</description>
        <label>Quote Stage Begin Date</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

mdapi/sfdx-unum-poc-alpha-deploys/classes/CustomerAndProspectAcctOpptCnt.cls
/**
*
*@ Author     : Aruna Rapolu
*@ Created    : 6/9/2014
*
*Class will display customer and prospect account opportunities on CustomerAndProspectOpportunities vf pages
*
* Log #1 - 11/18/2014 - Nate Wallace - Removed reference to Opportunity.Sub_Type__c field.
* Log #2 - 10/12/2016 - Karthik Polasi - After checking the VF page, removed unwanted fields in the query that are not being used on this page.
* Log #3 - 10/18/2016 - Karthik Polasi - Removed Quote references as a part of Opp/Quote project and added the new field Quote Stage Being date
**/

public  class CustomerAndProspectAcctOpptCnt{

    public CustomerAndProspectAcctOpptCnt(ApexPages.StandardController controller) {

    }
    public CustomerAndProspectAcctOpptCnt() {

    }

   /**
   *
   *@Author : Auna Rapolu
   *@created : 6/9/2014
   *Method will get account id from the vf page url
   *
   **/ 
   public string accountId{
       get{
           return accountId= Apexpages.currentPage().getParameters().get('accId');
       }set;
   }
   /**
   *
   *@Author : Auna Rapolu
   *@created : 6/9/2014
   *Method is used on vf page to display account name
   *
   **/ 
   public string accountName{
       get{
           Account accObj=[select id,Name from Account where Id=:accountId];
          return  accountName=accObj.Name;
       }set;
   } 
   /**
   *
   *@Author : Auna Rapolu
   *@created : 6/9/2014
   *Method  get all the opportunities and quotes of realted to account 
   *
   **/ 
   public list<Opportunity> oppList{
      
        get{
            return oppList=[select id,Name
                                     ,PRIM_FIELD_OFC_NM__c
                                     ,PRIM_SALE_REP_ID__r.Name
                                     ,PRIM_SALE_REP_ID__c
                                     ,Broker__c
                                     ,Broker__r.Name
                                     ,Type
                                     ,StageName 
                                     ,QUOTE_STAGE_BEGIN_DT__c
                                     ,CloseDate
                                     
                                 from Opportunity
                                       
                                       where AccountId=:accountId ORDER BY CloseDate DESC];
        
        }set;
   }
   
}